// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuzykaAlbumy.Data;

namespace MuzykaAlbumy.Migrations
{
    [DbContext(typeof(MuzykaAlbumyContext))]
    [Migration("20210102124054_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MuzykaAlbumy.Modele.Albumy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dataWydania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataZakupu")
                        .HasColumnType("datetime2");

                    b.Property<string>("gatunekMuzyczny")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nazwaAlbumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wersjaAlbumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wykonawca")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Albumy");
                });
#pragma warning restore 612, 618
        }
    }
}
